baseURL = "https://chiefhustler.com/"
languageCode = "en-us"
title = "The Chief's Blog"
theme = "yinyang"
DefaultContentLanguage = "en"
enableEmoji = true

ignoreErrors = ["error-remote-getjson"]

googlefonts = "http://fonts.googleapis.com/css?family=Itim|Limelight"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[author]
  name = "chiefhustlr"
  homepage = "https://twitter.com/chiefhustlr"

[languages]
  [languages.en]
    contentDir = "content"
    languageName = "English"
    weight = 1
  

[params]
mainSections = ["posts", "diary", "weekly-recap"]

headTitle = "Chief Hustler"
#disqusShortname = 'https-chiefhustler-com'
#disqus = "https-chiefhustler-com" # disqus account name
graphcomment = true
extraHead = "<!-- Global site tag (gtag.js) - Google Analytics --> <script async src='https://www.googletagmanager.com/gtag/js?id=G-4R1BEBSNLV'></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-4R1BEBSNLV');</script>"

[[params.socials]]
name = "| Investing Diary "
link = "/diary/"

[[params.socials]]
name = "| Resources "
link = "/posts/value-investing-resources"

[[params.socials]]
name = "| Quotes "
link = "/posts/quotes"

[[params.socials]]
name = "| Crazyland "
link = "/categories/crazyland/"

postHeaderContent = ""
postFooterContent = "<br/><br/><p>Connect with me on [twitter](https://twitter.com/chiefhustlr)</p>"
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
# extraCSSFiles = ["css/custom_style.css"]

